name: template
description: Default template.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  easy_localization: ^3.0.1
  hooks_riverpod: ^2.3.2
  flutter_hooks: ^0.18.6
  dio: ^5.0.3
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  go_router: ^7.0.0
  cached_network_image: ^3.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  lint: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - assets/lang/
    - assets/images/
    - assets/icons/